### ISSUE TITLE
[FEATURE] Home page(메인 화면)

### ISSUE THREAD

**Issue by Yerin00** [ToonInUs/Front#12]
# ISSUS: ✅FEATURE
Feature 작업 사항을 입력해주세요.

---

## Description
---
사이트에 들어오면 가장 먼저 보이는 홈 화면을 만들 예정입니다.
주요 기능은 각 카테고리 별로 분류된 웹툰을 swiper형태로 사용자에게 보여주는 것입니다.
<br />
<br />

## Todo
---
- [ ] 메인화면 상단 slider
- [ ] 취향 태그설정하러가기 버튼
- [ ] 신작웹툰, 인기웹툰, 내 취향 추천, 관심웹툰 카테고리 만들기
- [ ] tap component
- [ ] swiper component

## ETC
---
기타사항
