### ISSUE TITLE
[FEATURE] MorePage(더보기 페이지)

### ISSUE THREAD

**Issue by Yerin00** [ToonInUs/Front#19]
# ISSUS: ✅FEATURE
Feature 작업 사항을 입력해주세요.

---

## Description
---
로그아웃과 각종 설정을 담당하는 페이지입니다.
회원가입, 로그인과 동시에 username을 불러오는 것과 로그아웃 기능을 확인하기위해
미리 만들예정입니다.
<br />
<br />

## Todo
---

- [x] pageTitle 컴포넌트 사용
- [x] username 표시
- [x] username 변경 페이지
- [x] 로그아웃 버튼
- [x] 공지사항, 설정 버튼

## ETC
---
기타사항
